### ISSUE TITLE
关于检测和部署的一些想法

### ISSUE THREAD

**Issue by lukun199** [JiaPai12138/Crossfirer#14]
退坑好久好久了，周五在B站上刷到CF各种大哥的视频，顺手翻了一下这个话题。
实话说我真没想到YOLO还能用在这（也算是一个落地 /手动笑哭），很有意思。
个人感觉视觉检测比较难区分敌友、干扰以及识别远处的小物体。准确率的瓶颈都可能是比较难突破的，这个任务的难度比较大，在用户层面能获取到的数据比较有限。不过每一个新东西都是一点点走出来的，然后逐渐完善，给你一个star。
想到一个伦理方面的问题，这个东西可能不是很乐于接受。不同于修改内存的纯游戏方式，视觉引导的击杀拿到真实的战争上，也是没有什么区别的，我不知道这个东西会不会有一些潜在的争议，建议也稍微考虑一下。另外在国服运行还是有点不太好，建议在单机上部署测试效果。嗯。

**Comment by JiaPai12138** [comment]
多谢支持
其实就是写着玩玩，也算练习python
这主要就是打人机测试的，实战效果到平均水准就封顶了
敌友大致能分，只要训练时的标注做好(可惜CF皮肤角色过多失去了兴致)。小物体用yolov4-tiny准确不高，yolov5m可能好一些
你说的瓶颈我是不准备完整突破的，那样的话就太恶龙了
伦理的问题也有考虑到，刻意不分敌友也是这个原因，开源也有这个原因(方便被反外挂之类的针对)
