### ISSUE TITLE
自己写的AHK脚本怎么在CF里用?

### ISSUE THREAD

**Issue by TanixLu** [JiaPai12138/Crossfirer#3]
在其它环境能用,一进CF脚本就没用了

**Comment by JiaPai12138** [comment]
具体一点呢？哪个区的CF？国服还是西方服？西方服更新64位前用我的脚本使用办法可以正常玩，更新后似乎更没有限制了。注意那些鸡肋的bat脚本和ps1脚本，我也不知道原因但的确有效

**Comment by JiaPai12138** [comment]
没回复我关了哈
