### ISSUE TITLE
bat闪退

### ISSUE THREAD

**Issue by Vrusk7** [JiaPai12138/Crossfirer#32]
在打开Crossfirer_v2.x的bat时会直接闪退和神经网络的热键只有1  2有效并且只能单点 不能连发

**Comment by JiaPai12138** [comment]
不准备维护了
AHK你需要换类名自行编译 最好改一下扩展名
闪退通过管理员cmd打开看看有没有报错
神经自瞄那个确实只有主武器按键有效
也确实只能单点
