### ISSUE TITLE
CF的云游戏正在内测中

### ISSUE THREAD

**Issue by wysnxzm** [JiaPai12138/Crossfirer#4]
云游戏无法使用取色,像素颜色会一直变化
只能用识图+渐变实现
可以现在就尝试弄

**Comment by JiaPai12138** [comment]
屏幕取色还是可以的吧？ahk里的颜色搜索也允许设置渐变色的。
识图我试过，用ahk的不靠谱（比如控制枪口水平移动的脚本里），只能用机器学习的方法但我还不会
