### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Shinku9527** [JiaPai12138/Crossfirer#5]
大佬，自动开火部分无法正常开火

**Comment by JiaPai12138** [comment]
针对Crossfire West 版本，UI界面消失的话需要按一下右边的Alt键恢复界面，脚本才能正常运行。
你现在再试试呢？
如果遇到红名并且开启自火（UI界面提示“搜寻敌人中”）情况下还没反应，可以请提供视频吗？谢谢

**Comment by JiaPai12138** [comment]
嗯我好像在这两天的更新中修复了这个问题,但忘了具体哪些代码了。。。

**Comment by JiaPai12138** [comment]
没后续问题就关了哈
